Step 1: Load & inspect all 4 datasets

In [24]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [25]:
# Load all 4 raw files
camp_df = pd.read_csv('../data/raw/campaign_performance.csv')
store_sales_df = pd.read_csv('../data/raw/store_sales.csv')
cust_df = pd.read_csv('../data/raw/customers.csv')
web_df = pd.read_csv('../data/raw/website_sessions.csv')

In [26]:
# Inspect each dataframe

print(camp_df.shape)
print(camp_df.dtypes)
print(camp_df.isnull().sum())
print(camp_df.duplicated().sum())
sales_df.describe()

(13337, 14)
date                    object
channel                 object
campaign                object
impressions              int64
clicks                   int64
spend_zar              float64
conversions              int64
revenue_zar            float64
ctr_pct                float64
cpc_zar                float64
conversion_rate_pct    float64
roas                   float64
is_weekend               int64
is_promo_period          int64
dtype: object
date                     0
channel                  0
campaign                 0
impressions              0
clicks                   0
spend_zar              401
conversions              0
revenue_zar              0
ctr_pct                  0
cpc_zar                  0
conversion_rate_pct      0
roas                     0
is_weekend               0
is_promo_period          0
dtype: int64
118

,units_sold,unit_price_zar,discount_pct,revenue_zar,is_promo_period
count,22552.000000,23012.000000,23012.000000,23012.000000,23012.000000
mean,77.986742,884.779517,8.585738,67724.100615,0.328524
std,50.751841,489.157243,8.632416,61346.576568,0.469687
min,0.000000,159.200000,0.000000,-226648.800000,0.000000
25%,39.000000,499.000000,0.000000,22218.300000,0.000000
50%,73.000000,799.000000,5.000000,51271.000000,0.000000
75%,107.000000,1299.000000,20.000000,94190.400000,1.000000
max,325.000000,1899.000000,20.000000,475509.600000,1.000000

In [27]:
# Fixing null value issue
camp_df['spend_zar'].fillna(0, inplace=True) 
camp_df.drop_duplicates(inplace=True)
camp_df['channel'] = camp_df['channel'].str.title()

In [28]:
print(store_sales_df.shape)
print(store_sales_df.dtypes)
print(store_sales_df.isnull().sum())
print(store_sales_df.duplicated().sum())
store_sales_df.describe()

(23012, 9)
date                object
store               object
product             object
units_sold         float64
unit_price_zar     float64
discount_pct       float64
revenue_zar        float64
province            object
is_promo_period      int64
dtype: object
date                 0
store                0
product              0
units_sold         460
unit_price_zar       0
discount_pct         0
revenue_zar          0
province             0
is_promo_period      0
dtype: int64
0

,units_sold,unit_price_zar,discount_pct,revenue_zar,is_promo_period
count,22552.000000,23012.000000,23012.000000,23012.000000,23012.000000
mean,77.986742,884.779517,8.585738,67724.100615,0.328524
std,50.751841,489.157243,8.632416,61346.576568,0.469687
min,0.000000,159.200000,0.000000,-226648.800000,0.000000
25%,39.000000,499.000000,0.000000,22218.300000,0.000000
50%,73.000000,799.000000,5.000000,51271.000000,0.000000
75%,107.000000,1299.000000,20.000000,94190.400000,1.000000
max,325.000000,1899.000000,20.000000,475509.600000,1.000000

In [29]:
# Fixing null value issue
store_sales_df['units_sold'].fillna(store_sales_df['units_sold'].median(), inplace=True)
store_sales_df = store_sales_df[store_sales_df['revenue_zar'] >= 0]

In [30]:
print(cust_df.shape)
print(cust_df.dtypes)
print(cust_df.isnull().sum())
print(cust_df.duplicated().sum())
cust_df.describe()

(8080, 13)
customer_id             object
signup_date             object
last_purchase_date      object
age_group               object
gender                  object
province                object
acquisition_channel     object
num_purchases            int64
avg_order_value_zar    float64
total_clv_zar          float64
customer_segment        object
churned                  int64
email_opt_in             int64
dtype: object
customer_id              0
signup_date              0
last_purchase_date       0
age_group              320
gender                   0
province               161
acquisition_channel      0
num_purchases            0
avg_order_value_zar      0
total_clv_zar            0
customer_segment         0
churned                  0
email_opt_in             0
dtype: int64
80

,num_purchases,avg_order_value_zar,total_clv_zar,churned,email_opt_in
count,8080.000000,8080.000000,8080.000000,8080.000000,8080.000000
mean,4.741584,856.767483,4054.861106,0.702351,0.718936
std,3.874700,300.344388,3766.842955,0.457252,0.449547
min,1.000000,150.000000,150.000000,0.000000,0.000000
25%,2.000000,651.040000,1259.005000,0.000000,0.000000
50%,4.000000,856.680000,2896.545000,1.000000,1.000000
75%,7.000000,1061.267500,5580.042500,1.000000,1.000000
max,28.000000,1989.090000,33798.670000,1.000000,1.000000

In [31]:
cust_df['age_group'].fillna('unknown', inplace=True)
cust_df['province'].fillna('unknown', inplace=True)
cust_df.drop_duplicates(subset='customer_id', keep='first', inplace=True)

In [32]:
print(web_df.shape)
print(web_df.dtypes)
print(web_df.isnull().sum())
print(web_df.duplicated().sum())
print(web_df.describe())

(21831, 12)
date                         object
source_medium                object
device_category              object
sessions                      int64
bounce_rate_pct             float64
pages_per_session           float64
avg_session_duration_sec    float64
transactions                  int64
revenue_zar                 float64
conversion_rate_pct         float64
landing_page                 object
is_promo_period               int64
dtype: object
date                          0
source_medium                 0
device_category               0
sessions                      0
bounce_rate_pct             546
pages_per_session             0
avg_session_duration_sec      0
transactions                  0
revenue_zar                   0
conversion_rate_pct           0
landing_page                  0
is_promo_period               0
dtype: int64
0
           sessions  bounce_rate_pct  pages_per_session  \
count  21831.000000     21285.000000       21831.000000
mean     150.427466        54.895429           3.495823
std      112.326294        11.555158           1.160857
min       10.000000        35.000000           1.500000
25%       63.000000        44.900000           2.480000
50%      123.000000        54.800000           3.490000
75%      213.000000        64.900000           4.500000
max      639.000000        75.000000           5.500000

       avg_session_duration_sec  transactions   revenue_zar  \
count              21831.000000  21831.000000  21831.000000
mean                 162.970505      5.324905   4787.252291
std                   67.781322      5.851203   5890.197674
min                   45.000000      0.000000      0.000000
25%                  104.200000      1.000000   1054.850000
50%                  163.500000      3.000000   2742.830000
75%                  221.800000      7.000000   6336.590000
max                  280.000000     47.000000  61621.160000

       conversion_rate_pct  is_promo_period
count         21831.000000     21831.000000
mean              3.750341         0.326371
std               1.722946         0.468895
min               0.800000         0.000000
25%               2.310000         0.000000
50%               3.690000         0.000000
75%               5.090000         1.000000
max               7.800000         1.000000

In [33]:
web_df['bounce_rate_pct'].fillna(web_df['bounce_rate_pct'].median(), inplace=True)

Step 2: Fix dates and data types

In [34]:
# Convert date columns to datetypes
camp_df['date'] = pd.to_datetime(camp_df['date'])
store_sales_df['date'] = pd.to_datetime(store_sales_df['date'])
cust_df['signup_date'] = pd.to_datetime(cust_df['signup_date'])
cust_df['last_purchase_date'] = pd.to_datetime(cust_df['last_purchase_date'])
web_df['date'] = pd.to_datetime(web_df['date'])

# Add useful time columns
camp_df['month'] = camp_df['date'].dt.month
camp_df['year'] = camp_df['date'].dt.year
camp_df['day_name'] = camp_df['date'].dt.day_name()
camp_df['week_num'] = camp_df['date'].dt.isocalendar().week

Step 3: Save clean files

In [35]:
# Save clean files
camp_df.to_csv('../data/clean/campaign_performance_clean.csv', index=False)
store_sales_df.to_csv('../data/clean/stores_sales_clean.csv', index=False)
cust_df.to_csv('../data/clean/customer_clean.csv', index=False)
web_df.to_csv('../data/clean/website_sessions_clean.csv', index=False)

print('All clean files saved✅')

All clean files saved✅